language: java
jdk: openjdk11

service:
  - docker

install: true

script:
  - mvn clean verify install

deploy:
  - provider: script
    script:
      - cd capella-application && mvn clean package -DskipTests -Pproduction jib:build
      - cp .travis.settings.xml $HOME/.m2/settings.xml && cd capella-application && mvn deploy
    on:
      branch: master
  - provider: script
    script:
      - cd capella-application && mvn clean package -DskipTests -Pdevelop jib:build
      - cp .travis.settings.xml $HOME/.m2/settings.xml && cd capella-application && mvn deploy
    on:
      branch: dev

cache:
  directories:
  - $HOME/.m2