language: java
jdk: openjdk11

service:
  - docker

install: true

script:
  - mvn clean verify install

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - cd capella-application && mvn clean install -DskipTests -Pproduction jib:build
      - cp .travis.settings.xml $HOME/.m2/settings.xml && cd capella-service && mvn deploy -DskipTests
    on:
      branch: master

cache:
  directories:
  - $HOME/.m2